language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
    - composer global require fabpot/php-cs-fixer
    - export PATH=$PATH:$HOME/.composer/vendor/bin
    - composer install --dev

script:
    - phpunit
    - php-cs-fixer --diff --dry-run -v fix .
